[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig_contract = "DikY9r1rRQojX8v9jSa7eV5C4sFgBn5XyadrLUVNN635"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
